#!/bin/bash
if [ $# -ne 1 ];
then
	echo "Usage : $0 <volume{+/-}"
	echo "Example $0 5+"
	exit 1
fi
amixer set Master $1>/dev/null
pkill simixer
/home/simula67/Coding/qt/simixer/simixer -style motif `amixer get Master|grep '\['|awk '{ print $4 }'|sed s/'\['//|sed s/'\]'//|sed s/'%'//`
