######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 25 03:32:27 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += age.cpp
