######################################################################
# Automatically generated by qmake (2.01a) Thu May 19 18:10:25 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += shutdown.h
SOURCES += shutdown.cpp
