######################################################################
# Automatically generated by qmake (2.01a) Wed Jan 6 03:16:10 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
